### PR TITLE
Fixes #58

### LINKED ISSUE #58: Print all changes instead of last 5
Is it possible to print out all changes instead of the last 5?

### PR DESCRIPTION
**Pull request by ashwanthkumar**
Adding a new config 'truncate-changes', which is useful to display all changes or only latest 5 changes. See the issue #58  for more context.

@jdavisp3 Please have a look at this PR.

### CODE REVIEW

**Review by jdavisp3 — APPROVED** [review]
Nice! The changes look right to me.

Did you consider making the max number of changes configurable instead? (With, say, `null` indicating no maximum)

**Comment by ashwanthkumar** [comment]
@jdavisp3 I did consider but 2 reasons why I didn't go with that approach
1. I'm not a huge fan of `null`. Had this been scala, I would prefer to use [`Option`](http://alvinalexander.com/scala/using-scala-option-some-none-idiom-function-java-null) but alas Java doesn't support it :( I have an [implementation in Java](https://github.com/ashwanthkumar/my-java-utils/tree/master/src/main/java/in/ashwanthkumar/utils/lang/option) but that isn't great for readability. 
2. I was wondering why would someone want latest n changes over just 5? I mean it might or might not be complete anyways right? Also in my experience 5 looks pretty well for build failures assuming the pushes are small and incremental. 

What do you think?

**Comment by jdavisp3** [comment]
Yep, makes sense to me! :shipit:

**Comment by ashwanthkumar** [comment]
Thanks @jdavisp3

**Pull request merged**
