### PR TITLE
Much better failure reporting and tests

### PR DESCRIPTION
**Pull request by juhasipo**
I fixed the merge conflicts of pull request #15. I also added a bunch of tests and fixed a couple of bugs I found.

### CODE REVIEW

**Comment by ashwanthkumar** [comment]
@manojlds @tamizhgeek - Guys can you please test these changes in our environment and revert back with feedback?

**Comment by tamizhgeek** [comment]
@ashwanthkumar Deployed this in our setup. Will revert back with feedback by tomorrow.

**Comment by tamizhgeek** [comment]
@ashwanthkumar No issues in our setup so far. :+1: from me.

**Comment by manojlds** [comment]
This is a huge improvement, thanks @juhasipo :+1:

**Comment by ashwanthkumar** [comment]
Merging this now, thanks @juhasipo and @emk

**Comment by emk** [comment]
Thank you for merging it!

**Pull request merged**
