### PR TITLE
Add information about adding plugin in GoCD hosted on K8s

### PR DESCRIPTION
**Pull request by mohamednajiullah**
This PR should help people who have their GoCD setup hosted on Kubernetes to add this plugin to their instance.

It contains information on how to add the plugin jar file and also on how to mount the config file.

### CODE REVIEW

**Comment by mohamednajiullah** [comment]
The PR only updates the README.md. I don't know why the CI check is failing.

Is it possible to retrigger it?

**Review by ashwanthkumar — COMMENTED** [review]
Thank you so much for this PR. You might want to add some spaces between `###...` heading markups and the text for the Github to render it properly.

**Comment by ashwanthkumar** [comment]
One the JDK that this project was using is no longer supported on Travis. I've updated the matrix, once you fix the markup the build should go green post that.

**Comment by mohamednajiullah** [comment]
Sorry about that. I used an editor that showed that the formatting was proper.

I've corrected it. Please confirm.

**Comment by ashwanthkumar** [comment]
Merging this. Thanks!

**Pull request merged**
