### PR TITLE
Fixed GoNotificationMessage for Gson parser

### PR DESCRIPTION
**Pull request by BharathMG**
Modified GoNotficationMessage class which was failing for Gson parser.. Thanks for the plugin! :+1:

### CODE REVIEW

**Comment by ashwanthkumar** [comment]
@BharathMG Please help me understand the changes. What was the error? From the [documentation](http://www.go.cd/documentation/developer/writing_go_plugins/notification/version_1_0/stage_status_notification.html), I don't see a change in schema of the message. 
I guess I'm missing something here.

**Comment by BharathMG** [comment]
Hey,
I guess the documentation is outdated. The new API changes were updated on https://github.com/srinivasupadhya/email-notifier/commit/ea9788f7f4dba06f1b139accc36536d845fd7012 this commit.

**Comment by srinivasupadhya** [comment]
Yes! @ashwanthkumar I wanted to notify you of the change in payload. There is more data available now & made the top level data redundant. So got rid of them. [reference](https://github.com/gocd/gocd/pull/968#issuecomment-84364723). Sorry about that!

**Comment by ashwanthkumar** [comment]
@srinivasupadhya  :+1: No worries :)

@BharathMG Thanks for catching it. I'm merging this now.

**Pull request merged**
