### PR TITLE
Misc tweaks, including CANCELLED & reporting the causes of builds

### PR DESCRIPTION
**Pull request by emk**
Thank you for a great GoCD plugin! I added a few minor features, including:
- Support for notifications on CANCELLED.
- Displaying the `trigger_message` field in Slack messages. This will typically give the git committer. To get this, we had to tie into the GoCD JSON API.

If any of these patches look useful, please feel free to merge them upstream!

### CODE REVIEW

**Comment by stevendgonzales** [comment]
Love this plugin so far!

Is this PR something that will be merged? I saw API changes in this PR in (handle api update + cleanup c3c37df) Does that mean the current version of plugin will be incompatible with a future version of Go.CD?

**Comment by stevendgonzales** [comment]
adding another not here.  I tested the existing release of this plugin (which i have working with older 15.x version of go.cd) with the latest release of go.cd (15.1.0-1845) and the plugin is not compatible with the API in this release.  I cloned the emk:tweaks branch from this PR and built the jar, and was able to verify that the plugin works.

Any chance this can get merged and released as a 2.0?

**Comment by stevendgonzales** [comment]
@emk These changes are not compatible with 14.x versions of go.cd, you should probably update the POM to bump the version of this plugin since the API has changed.

**Comment by srinivasupadhya** [comment]
I think the API change was done by @BharathMG that has got merged & hence there are conflicts.

**Comment by srinivasupadhya** [comment]
@stevendgonzales the [go-plugin-api](https://github.com/ashwanthkumar/gocd-slack-build-notifier/blob/master/pom.xml#L19) dependency is a provided one (provided by Go Server at runtime) & hence is not packaged. The `go-plugin-api` is written in a way that does not require plugin devs to update every release, so that does not need to be updated.

The Notification end-point was added in 15.1 so this will not work for anything < v15.1.

Hope that helps.

**Comment by ashwanthkumar** [comment]
All I'm really sorry for the delay. I'll have a look at these changes this weekend and get back to you guys.

**Comment by stevendgonzales** [comment]
@srinivasupadhya Sorry for the confusion.  What I should have stated was that the existing of this plugin worked with go-server 15.1.0-1535, but does not work with >= 15.1.0-1845.  After merging these changes, which include an API tweak, it will work.  That is why i suggested a possible version bump of the plugin from 10. to 2.0 (or whatever seems reasonable)

**Comment by superbeeny** [comment]
Hi guys, what's the status of this?

**Comment by emk** [comment]
Just a quick update: I agree that the pom stuff should be updated as necessary, and I'm pretty certain that this version of the code occasionally fails to distinguish between "Failed" and "Broken" states, because I wasn't aware of all the nuances of the JSON. In particular:
- If you have a pipeline with stages A & B, and B fails, then when you push a fix, it will report _both_ A and B as "Fixed". It should report A as "Passing" and B as "Fixed".
- Similarly, if you re-run individual pipeline stages, the distinction between "Passing" and "Fixed" can sometimes get confused in weird ways.

It still works pretty well in practice, but I've been looking for a spare moment to investigate the JSON returned by the GoCD API in hopes of cleaning up these occasional oddities.

**Pull request merged**
