### PR TITLE
Much better failure reporting

### PR DESCRIPTION
**Pull request by emk**
The current version of gocd-slack-build-notifier has several major limitations. Many of these limitations are my fault—one of my previous patches had some pretty serious issues that didn't become apparent until we had used it for a while.
- The distinctions between _Passed_/_Fixed_ and _Failed/Broken_ are hopelessly incorrect if you have multi-stage pipelines or if you re-run pipeline stages manually. (This is totally my fault; my last patch made too many simplifying assumptions.) To fix this, we implement a new `previousRun` function that finds the previous time a stage was run, and we use that for comparison.
- We use raw `JsonElement`s instead of Java wrapper objects. (Again, my fault.)

The version also adds some major new features:
- We now walk the entire pipeline graph to find the original commits that triggered a pipeline run, and summarize them in our messages. This makes it much easier to diagnose complicated pipeline failures, because we now print out the commits that might have broken the build.
- We special-case git repositories stored on GitHub, and construct URLs that allow us to click on Slack messages and see the change. It would be nice to extend this to other git hosting providers.

This has been tested against a very large GoCD setup under heavy development by a team, and it appears to be a large improvement over the current reporting code.
### Example output

Let's assume that we have a **staging** pipeline which depends on two pipelines, **microservice1** and **microservice2**. A developer makes a change to **microservice1** that looks good in isolation, but the change causes **staging**'s acceptance tests to fail. We now walk the pipeline graph backwards from **staging** to the underlying **microservice1** change and report it along with a GitHub link:

> **Stage [staging/770/AcceptanceTests/1] is BROKEN**
> Triggered by microservice1/352/TestAndPublish/1. See details - https://gocd.example.org/go/pipelines/staging/770/AcceptanceTests/1
> URL: git@github.com:exampleorg/microservice1.git, Branch: master
> https://github.com/exampleorg/microservice1/commit/bff403 Accidentally break microservice interaction - J. Random Hacker jrandomhacker@example.org

Unfortunatey, gocd-slack-build-notifier uses raw text attachments. We should probably switch to a more featureful Slack client library and clean up the formatting. But in practice, this already seems to be a major improvement.

### CODE REVIEW

**Comment by ashwanthkumar** [comment]
Thank you so much for doing this. I wanna test these at our setup and merge the changes.

**Comment by vivanov1410** [comment]
Ping, can anybody fix build problems and merge?

**Comment by RehanSaeed** [comment]
Any updates on this PR?

**Comment by just2jays** [comment]
+1

Pretty excited to get this pull request merged and implemented in our GoCD setup ASAP!

**Comment by ashwanthkumar** [comment]
Fixed via #33. Closing this.

**Pull request closed without merging**
